name: MATSim.org
description: "MATSim | Multi-agent Transport Simulation"
url: http://matsim.org
lsi: false
kramdown:
  input: GFM
timezone: Europe/Brussels
permalink: /:categories/:year/:title
gems:
  - jekyll-sitemap
