name: MATSim.org
description: "MATSim | Multi-agent Transport Simulation"
url: https://matsim.org
lsi: false
kramdown:
  input: GFM
timezone: Europe/Brussels
permalink: /:categories/:year/:title
plugins:
  - jekyll-sitemap
page_gen:
  - data: 'extensions-main'
    template: 'extension'
    name: 'name'
    dir: 'extension'
    index_files: true
  - data: 'extensions-external'
    template: 'extension'
    name: 'name'
    dir: 'extension'
    index_files: true
  - data: 'extensions-contrib'
    template: 'extension'
    name: 'name'
    dir: 'extension'
    index_files: true
